### ISSUE TITLE
Suggestion: Add table of contents to left pane/column

### ISSUE THREAD

**Issue by reblake** [ESIPFed/bds-primer-best-practices#85]
**What section of the best practices is the issue related to?**
This is related to the whole guide.  

**Short description of issue**
It would be helpful to the readers of the guide to have the headings with sections 1-6 show up in the left pane/panel so that the content sections are more visible. 

**Suggested solution**
Add this to the `_quarto.yml` file
```
format:  
    html:  
      toc: true  
      toc-location: left  
      toc-title: ""  
```
